In [1]:
import numpy as np

In [15]:
Q1 = np.array([[1,2],[3,4]])
print(Q1)

[[1 2]
 [3 4]]


In [18]:
Q2 = np.random.random((3,4))
print(Q2)

[[0.89535694 0.76157348 0.0089237  0.6479549 ]
 [0.29548729 0.63595073 0.00812728 0.04441262]
 [0.78378578 0.76076108 0.86412043 0.981331  ]]


In [19]:
Q3_1 = np.zeros((2,2))
print(Q3_1)
Q3_2 = np.ones((2,2))
print(Q3_2)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]


In [21]:
Q4 = np.random.random((6,3))
print(Q4)
Q4 = Q4.transpose()
print(Q4)

[[0.83269382 0.29490921 0.90936788]
 [0.36909232 0.07714533 0.02467313]
 [0.99997493 0.13393888 0.82227205]
 [0.00260551 0.75537242 0.51551347]
 [0.74585627 0.82969577 0.06562943]
 [0.97310101 0.172697   0.7610849 ]]
[[0.83269382 0.36909232 0.99997493 0.00260551 0.74585627 0.97310101]
 [0.29490921 0.07714533 0.13393888 0.75537242 0.82969577 0.172697  ]
 [0.90936788 0.02467313 0.82227205 0.51551347 0.06562943 0.7610849 ]]


In [22]:
Q5_1 = np.random.random((3,4))
Q5_2 = np.random.random((4,5))
print(Q5_1)
print(Q5_2)

dot_Product = Q5_1 @ Q5_2
print(dot_Product)

[[0.16616384 0.42300033 0.87916697 0.86247213]
 [0.31433703 0.43908655 0.56794065 0.40541719]
 [0.13515814 0.57342369 0.14287889 0.07590148]]
[[0.94494386 0.81271687 0.68257158 0.04736219 0.53536278]
 [0.31708946 0.42712851 0.66995228 0.12764114 0.18754545]
 [0.46869765 0.73896416 0.50449771 0.87185762 0.84898945]
 [0.77668031 0.65909179 0.89563236 0.8110722  0.04822537]]
[[1.37307306 1.53384084 1.61280442 1.52789772 0.95628624]
 [1.01733255 1.12990831 1.15835407 0.89491919 0.75236004]
 [0.43546165 0.51037933 0.61648351 0.26572547 0.30486469]]
